// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/task/task.proto

// 服务名

package task

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/any"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for TaskService service

func NewTaskServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for TaskService service

type TaskService interface {
	// 创建任务
	Create(ctx context.Context, in *Task, opts ...client.CallOption) (*Response, error)
	// 删除任务
	Delete(ctx context.Context, in *Task, opts ...client.CallOption) (*Response, error)
	// 修改任务
	Modfiy(ctx context.Context, in *Task, opts ...client.CallOption) (*Response, error)
	// 完成任务
	Finished(ctx context.Context, in *Task, opts ...client.CallOption) (*Response, error)
	// 搜索
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*Response, error)
}

type taskService struct {
	c    client.Client
	name string
}

func NewTaskService(name string, c client.Client) TaskService {
	return &taskService{
		c:    c,
		name: name,
	}
}

func (c *taskService) Create(ctx context.Context, in *Task, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "TaskService.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskService) Delete(ctx context.Context, in *Task, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "TaskService.Delete", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskService) Modfiy(ctx context.Context, in *Task, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "TaskService.Modfiy", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskService) Finished(ctx context.Context, in *Task, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "TaskService.Finished", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskService) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "TaskService.Search", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TaskService service

type TaskServiceHandler interface {
	// 创建任务
	Create(context.Context, *Task, *Response) error
	// 删除任务
	Delete(context.Context, *Task, *Response) error
	// 修改任务
	Modfiy(context.Context, *Task, *Response) error
	// 完成任务
	Finished(context.Context, *Task, *Response) error
	// 搜索
	Search(context.Context, *SearchRequest, *Response) error
}

func RegisterTaskServiceHandler(s server.Server, hdlr TaskServiceHandler, opts ...server.HandlerOption) error {
	type taskService interface {
		Create(ctx context.Context, in *Task, out *Response) error
		Delete(ctx context.Context, in *Task, out *Response) error
		Modfiy(ctx context.Context, in *Task, out *Response) error
		Finished(ctx context.Context, in *Task, out *Response) error
		Search(ctx context.Context, in *SearchRequest, out *Response) error
	}
	type TaskService struct {
		taskService
	}
	h := &taskServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&TaskService{h}, opts...))
}

type taskServiceHandler struct {
	TaskServiceHandler
}

func (h *taskServiceHandler) Create(ctx context.Context, in *Task, out *Response) error {
	return h.TaskServiceHandler.Create(ctx, in, out)
}

func (h *taskServiceHandler) Delete(ctx context.Context, in *Task, out *Response) error {
	return h.TaskServiceHandler.Delete(ctx, in, out)
}

func (h *taskServiceHandler) Modfiy(ctx context.Context, in *Task, out *Response) error {
	return h.TaskServiceHandler.Modfiy(ctx, in, out)
}

func (h *taskServiceHandler) Finished(ctx context.Context, in *Task, out *Response) error {
	return h.TaskServiceHandler.Finished(ctx, in, out)
}

func (h *taskServiceHandler) Search(ctx context.Context, in *SearchRequest, out *Response) error {
	return h.TaskServiceHandler.Search(ctx, in, out)
}
